# https://cloud.google.com/cloud-build/docs/speeding-up-builds
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
    _IMAGE: 'gcr.io/whiteblock/binance/dexter-data'
timeout: '30m'
steps:
# allow these steps to fail, they try to pull cache first
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull $_IMAGE:$BRANCH_NAME || true' ]
# build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE:latest',
            '-t', '$_IMAGE:$BRANCH_NAME',
            '-t', '$_IMAGE:$COMMIT_SHA',
           '--cache-from', '$_IMAGE:$BRANCH_NAME',
            '.'
        ]
# push docker image tag(s) one branch, one immutable
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$COMMIT_SHA' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_IMAGE:$BRANCH_NAME' ]
images: [ '$_IMAGE:latest', '$_IMAGE:$COMMIT_SHA', '$_IMAGE:$BRANCH_NAME' ]
